### ISSUE TITLE
explore weboasis

### ISSUE THREAD

**Issue by trinib** [StanForever/awesome-websites#10]
check out [here ](https://weboasis.app/)and [here ]( https://start.me/u/JDLKQ5)see what is most awesome to add to your repo

**Comment by trinib** [comment]
here are some more [Links.txt](https://github.com/StanForever/awesome-websites/files/8395066/Links.txt)

**Comment by StanForever** [comment]
Hi @trinib please create a PR for adding these awesome websites. Thank you.
