### ISSUE TITLE
Adding os.directory

### ISSUE THREAD

**Issue by Mediashare** [StanForever/awesome-websites#8]
Hello, I have a proposal to add a site in the list: this website is https://os.directory (Online operating system).

What do you think?

**Comment by StanForever** [comment]
Hi @Mediashare this website is awesome! Please feel free to create PR so I can add it. Thanks!

**Comment by StanForever** [comment]
Closing this issue as it's been already addressed in this [PR](https://github.com/StanForever/awesome-websites/pull/9).
